name: geek_connect
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'
  # flutter: ">=3.0.0" ">=3.1.2"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.0.0
  iconsax: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

assets:
  - 'images/evento2.png'
  - 'images/evento3.png'
  - 'images/evento1.png'
  - 'images/evento4.png'
  - 'images/evento5.png'
  - 'images/evento6.png'
  - 'images/evento7.png'
  - 'images/evento8.png'
  - 'images/conta.png'
  - images/geeks.png
  - 'images/banner.png'
  - 'images/background.png'
  - 'images/imgmenu.png'

# fonts:
#   - family: Biotit
#     fonts:
#       - asset: assets/fonts/ #reescrever os nomes das fontes certo
#         weight: 700
